_format_version: "1.1"
_transform: true

services:
  - host: shiba-booking-prod-pbl-tpsota.mo5.mogenius.io
    name: shiba-booking
    port: 80
    protocol: http
    routes:
      - name: example_route
        paths:
          - /booking
        strip_path: true
